apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pwpusher-ruby-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    #app.kubernetes.io/part-of: pwpusher-ruby-web-app
spec:
  source:
    git:
      url: https://github.com/mshahat/PasswordPusher
      ref:
        branch: main