apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pwpusher-ruby-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: pwpusher-ruby-web-app
spec:
  build:
    env:
      - name: RAILS_SERVE_STATIC_FILES
        value: true
  env:
    - name: RAILS_SERVE_STATIC_FILES
      value: true
    - name: BPE_RAILS_SERVE_STATIC_FILES
      value: true
  params:
    - name: clusterbuilder
      value: tesco
    - name: gitops_ssh_secret
      value: github-ssh
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: mshahat
    - name: gitops_repository_name
      value: tap-gitops
  source:
    git:
      url: https://github.com/tanzu-solutions-engineering/PasswordPusher
      ref:
        branch: master
